
service: middlewareService

frameworkVersion: '2'

plugins:
 - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.8

provider:
  name: aws
  runtime: python3.8
  environment:
    RABBIT_URI: amqp://admin:adminpass@${file(../config.json):PUBLIC_IP}:5672
    MONGO_DB_URL: ${file(../config.json):MONGO_DB_URL}
    MONGO_DB_NAME: articles
    EMAIL_SENDER: ${file(../config.json):EMAIL_SENDER}
    AWS_REGION: ${file(../config.json):AWS_REGION}
    
functions:
  userService:
    runtime: python3.7
    handler: userRabbit.main