
service: ingestionService

frameworkVersion: '2'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.8

provider:
  name: aws
  runtime: python3.8
  environment:
    RABBIT_URI: amqp://admin:adminpass@${file(../config.json):PUBLIC_IP}:5672
    
functions:
  articleIngest:
    runtime: python3.8
    handler: articleIngestRabbit.main
    events:
     - http:
         path: users/create
         method: get


