
service: similarityService

frameworkVersion: '2'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.8

provider:
  name: aws
  runtime: python3.7
  environment:
    RABBIT_URI: amqp://admin:adminpass@ec2-52-207-231-70.compute-1.amazonaws.com:5672

functions:
  googleDork:
    runtime: python3.7
    handler: googleDorkRabbit.main
    events:
     - http:
         path: users/create
         method: get

