service: gqlAPI

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    TOKEN_SECRET: test
    RABBIT_URI: amqp://admin:adminpass@${file(../config.json):PUBLIC_IP}:5672
    
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    useChildProcesses: true
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true


functions:
  search:
    handler: src/functions/search.handler
    events:
      - http:
          path: search
          method: post
          cors:
            origin: '*'
            allowCredentials: true
      - http:
          path: search
          method: get
          cors:
            origin: '*'
            allowCredentials: true

  login:
    handler: src/functions/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
      - http:
          path: login
          method: get
          cors: true

  signup:
    handler: src/functions/signUp.handler
    events:
      - http:
          path: signUp
          method: post
          cors: true
      - http:
          path: signUp
          method: get
          cors: true